### PR TITLE
Button Customization: Text/Bg Color, Button Labels, and Bug Fixes

### PR DESCRIPTION
**Pull request by RohanModi-CA**
I appreciate your creation of this add-on.

I've noticed that the add-on wasn't compatible with a custom-button colors add-on (as expressed in #12), so I implemented my own color customization into the add-on. I added a config-dialog to deal with the new customization, and made it so that my additions were disabled by default. 

The new additions offer an additional layer of customization over the add-on mentioned in #12, since my v0.3.2 version also allows for the change of the background color of the buttons, not just the text, as that add-on does.

Also, #4 requests translation of the buttons. As you hinted at in your reply and #5, that's a lot of work. However, I made it so that you can just easily edit whatever is on the buttons, in the settings dialog.

I've tested the additions, and they are compatible from the latest Flatpak Anki (24.04) down to Anki 2.1.15, which is where the original add-on was tested until, according to the changelog. In doing so, I discovered that the v0.2.2 version-handling had a slight error, so 2.36-2.40 were actually not functional. I corrected that.

### CODE REVIEW

**Comment by RohanModi-CA** [comment]
Added customizability to the pass/fail extension and ensured backwards compatibility up to 2.1.15

**Comment by lambdadog** [comment]
Wow! Thank you for the major PR! Pass/Fail 2 has kind of been sitting on the wayside for some time since I stopped using Anki, but this addresses several of the issues that have cropped up.

That said, this seems to be an upstreaming of your own [fork](https://github.com/RohanModi-CA/passfail2) of Pass/Fail 2 with its own version history you've established, and while upstreaming is very appreciated, if it was just merged as-is it would impact Pass/Fail 2's own version history in a strange way with a jump from v0.2.2 to v0.3.2. I'd appreciate if you could revert the version change in the Makefile, and then I would be happy to merge and potentially put out a new v0.2.3 release on my end from the result (after some minor tweaking).

**Review by lambdadog — CHANGES_REQUESTED** [review]

**Comment by lambdadog** [comment]
Oh, and also if you could change the name of this PR to something more descriptive, as I'd like to squash-merge it, that would be appreciated!

**Comment by lambdadog** [comment]
Perfect! Thank you!

**Review by lambdadog — APPROVED** [review]

**Comment by RohanModi-CA** [comment]
Of course -- I might just suggest though that the jump from 0.2.2 to 0.2.3 doesn't reflect the not insignificant additions -- perhaps a 0.3.0 would be more appropriate. Your repository though, of course.

**Comment by lambdadog** [comment]
@RohanModi-CA That's a fair argument, but I'd like to get in one more change before v0.3.0. I've been thinking about it and some simplistic i18n shouldn't be too hard, and I'd prefer that to a stopgap like this PR adds for v0.3.0.

I may be putting too much emphasis on a relatively minor release, but while you're still in v0.x the minor releases tend to be a bigger deal than once you hit v1.x.

**Comment by RohanModi-CA** [comment]
Fair enough. 

Also, I just noticed the read-me makes reference to my old versioning system, so be sure to correct that before the next release.

**Comment by lambdadog** [comment]
Oops, good catch! Thank you.

**Comment by lambdadog** [comment]
Release out! I did end up ultimately removing the bg color implementation from v0.3.0 because I was uncomfortable with how dependent it was on Anki internals -- One of my big goals with this project is to make it as minimally dependent as possible. My hope is that even a hundred releases of Anki in the future the current version should stay working without any changes, as long as they don't do any massive overhauls (like v1.x to v2.x was). Anki doesn't make that easy with its addon framework, but the bg color change didn't measure up to that goalpost in my mind, since it reimplemented existing behavior that could change in a future version and cause breakages.

**Pull request merged**
